openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /department/saveDepartment:
    post:
      tags:
      - department-rest-controller
      summary: Save Department
      operationId: saveDepartment
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Department"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Department"
components:
  schemas:
    Department:
      type: object
      properties:
        departmentId:
          type: integer
          format: int64
        departmentName:
          type: string
        departmentCode:
          type: string
